### ISSUE TITLE
Breaking change (no more Node v4 support) in 1.2.2 patch version

### ISSUE THREAD

**Issue by bibekg** [rogeriopvl/gulp-jsonlint#66]
Looks like the version bump from 1.2.1 to 1.2.2 has a breaking change (no longer supports Node v4), contrary to semver practices.

**Comment by rogeriopvl** [comment]
@bibekg yeah, I thought about that, but technically the codebase of `gulp-jsonlint` still supports node v4, it's the dependencies that do not support. And this already happened a couple of versions ago because of the ranges we used. So it's tricky to leave the minor and patch stale and just bump the major.
